# Generated by Django 5.0.4 on 2024-04-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsapi', '0002_lens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_price_usd', models.FloatField()),
                ('lens_price_usd', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsapi.frame')),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsapi.lens')),
            ],
            options={
                'verbose_name': 'Glasses',
                'verbose_name_plural': 'Glasses',
            },
        ),
    ]
