# Generated by Django 5.0.4 on 2024-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('price_usd', models.FloatField(default=0.0)),
                ('price_gbp', models.FloatField(default=0.0)),
                ('price_eur', models.FloatField(default=0.0)),
                ('price_jod', models.FloatField(default=0.0)),
                ('price_jpy', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Frame',
                'verbose_name_plural': 'Frames',
            },
        ),
    ]
