# Generated by Django 5.0.4 on 2024-04-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prescription_type', models.CharField(choices=[('fashion', 'Fashion'), ('single_vision', 'Single Vision'), ('varifocal', 'Varifocal')], default='single_vision', max_length=15)),
                ('lens_type', models.CharField(choices=[('classic', 'Classic'), ('blue_light', 'Blue Light'), ('transition', 'Transition')], default='classic', max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('price_usd', models.FloatField(default=0.0)),
                ('price_gbp', models.FloatField(default=0.0)),
                ('price_eur', models.FloatField(default=0.0)),
                ('price_jod', models.FloatField(default=0.0)),
                ('price_jpy', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Lens',
                'verbose_name_plural': 'Lenses',
            },
        ),
    ]
